### ISSUE TITLE
How to release Kurento objects?

### ISSUE THREAD

**Issue by gtk2k** [oBears/Kurento.NET#1]
+1
Thanx create .NET Lib.

How to release Kurento objects?
(kurentoClient, pipeline and endpoints)
Thx.
I use it in unity.
https://drive.google.com/file/d/1REIOt7JAzL6SnLkAFiOn4GG28lQ3F_Rs/view?usp=sharing
(I can not execute after the second time)

**Comment by xv-chang** [comment]
Each object has a  "ReleaseAsync"  method,   kurentoClient , you need release ClientWebSocket.
this library is very simple,   only use ClientWebSocket  send message to kurento media server. you can try to view the sended message and received message.after that, compare with kurento protocol.
[this is kurento protocol ](https://doc-kurento.readthedocs.io/en/stable/features/kurento_protocol.html#kurento-protocol)

sorry ,my English is poor, maybe i don't understand what you mean

**Comment by gtk2k** [comment]
Thanx!
